name: Unit Tests

on:
  push:
    branches: ['Develop']
  pull_request:
    branches: ['Develop']

env:
  REACT_APP_SERVER_URL: https://team-furebo-e-commerce-bn.onrender.com

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: '0f994c643098c5170ff39f19aae8b135c283a936c3403694a592b13bd6d72c7e'
